### ISSUE TITLE
Index Error os.path.join(tempd, sorted(os.listdir(tempd))[0])

### ISSUE THREAD

**Issue by Akhil10204** [zerodhatech/pykiteconnect#56]
List index is out of range for first element. I also tried forced reinstall. I think, cloning and putting into site-package maually might work. Please look into the issue.

Exception:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip-19.0.2-py3.6.egg\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "c:\programdata\anaconda3\lib\site-packages\pip-19.0.2-py3.6.egg\pip\_internal\commands\install.py", line 355, in run
    session=session, autobuilding=True
  File "c:\programdata\anaconda3\lib\site-packages\pip-19.0.2-py3.6.egg\pip\_internal\wheel.py", line 980, in build
    python_tag=python_tag,
  File "c:\programdata\anaconda3\lib\site-packages\pip-19.0.2-py3.6.egg\pip\_internal\wheel.py", line 813, in _build_one
    python_tag=python_tag)
  File "c:\programdata\anaconda3\lib\site-packages\pip-19.0.2-py3.6.egg\pip\_internal\wheel.py", line 821, in _build_one_inside_env
    wheel_path = builder(req, temp_dir.path, python_tag=python_tag)
  File "c:\programdata\anaconda3\lib\site-packages\pip-19.0.2-py3.6.egg\pip\_internal\wheel.py", line 898, in _build_one_legacy
    return os.path.join(tempd, sorted(os.listdir(tempd))[0])
IndexError: list index out of range

**Comment by joeirimpan** [comment]
@Akhil10204 downgrade pip.
there is some issue on pip https://github.com/pypa/pip/commit/6cdecce71d540dba4df9b415dbdbd9bc4107be86

**Comment by vividvilla** [comment]
Please reopen the issue if required.
